variable "dataname" {}
variable "datauser" {}
variable "datapass" {}
variable "s3_bucket_name_blog" {}
variable "keyname" {}
variable "hostname" {}
variable "subdomain_name" {}
variable "repositoryname" {}
variable "endpointpath" {}
variable "imageid" {}
variable "git-user-name" {}
variable "git-repo-name" {}
variable "gittoken" {}